### PR TITLE
Move services to a separate directory

### PR DESCRIPTION
**Pull request by emmiegit**
Depends on #24 being merged first

### CODE REVIEW

**Review by notgull — COMMENTED** [review]
I'm uncomfortable with classifying some of these as services, especially the metadata files. Those are generally used by all of the other services as abstraction to access the database and I feel that they fit the role of helper functions more than seperate services.

In addition, some other modules (like the user and revision) don't have service parts to them yet so I'm hesitant to fully classify them as such.

I'm fine with the other changes here.

**Comment by emmiegit** [comment]
I'm not sure why metadata wouldn't count as a service for our purposes here, since it abstracts DB modifications without exposing the actual internals.

I don't see why characterizing them as helper functions would be more appropriate -- there's already a number of functions in metadata and I'd like to avoid utilities becoming too specialized.

As for user and revision, the name change reflects intentionality. They _should_ be separate services since they own their own domain and shouldn't expose any internals to other consumers.

**Comment by notgull** [comment]
My main issue is that metadata objects are used in pretty much every area of code (renderer, pagereq, revisions) and I think that making the metadata base itself on JSONRPC would either:

a). Require rewriting a lot of code to be JSONRPC sensitive in a way that I don't feel is necessary
b). Require implementing a lot of abstractionism to the point where I don't think it would be worth it

**Comment by emmiegit** [comment]
I don't really see what JSONRPC has to do with this. The objects can still be exported and used elsewhere, making metadata a service doesn't preclude that, nor does it require rewriting things.

The idea is just that the internal details of how metadata is stored is local to that service, and if another service wants that information they call a method rather than doing SQL themselves. (Which is one of the ideas in the service split, since having raw SQL everywhere gets to be a huge pain as the codebase grows).

**Pull request merged**
